### PR TITLE
feat: protect existing endpoints using runtime builtin ims auth

### PR DESCRIPTION
**Pull request by MichaelGoberling**
## Description
~_Opened as a draft for now as there's a bug in Runtime where if you specify security for one path, it checks for an ims token for all paths, so I haven't been able to fully test that list and get templates still works without providing an auth token_~

Auth details: 
- For deleting templates - require **template_registry.write** and a strict client allow list (see swagger for list)
- For creating templates - require **template_registry.write** and a strict client allow list (see swagger for list) 

**Other notable changes**
- Had to revert swagger to 2.0, since Runtime doesn't support 3.0+ for the scope and client validation features

## How Has This Been Tested?

`npm run test`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sandeep-paliwal** [comment]
@MichaelGoberling Can you validate the template registry api json ? I was getting some error when I tried it here `https://editor-next.swagger.io/`

**Comment by MichaelGoberling** [comment]
@sandeep-paliwal 

I see there's a few small warnings and then two errors about authorizationUrl being empty, i'll fix the warnings, but let me see if the empty authorizationUrl is needed or not, since that's how it's shown in the Runtime docs https://developer.adobe.com/runtime/docs/guides/using/creating_rest_apis/#scopes-validation

**Comment by MichaelGoberling** [comment]
@sandeep-paliwal 

okay I've fixed the swagger warnings, but proposing we keep the empty authorizationUrl

if we remove it, redocly complains about there not being an authorizationUrl, and whether or not we keep it or remove it, the swagger editor complains. We don't actually need this field, because Runtime automatically uses the IMS stage or prod url (and we shouldn't put a static value there because we _want_ Runtime to use stage or prod IMS based on the env we deploy to)

**Comment by MichaelGoberling** [comment]
runtime has fixed the security-for-all-paths bug! ready for review

**Review by arjuncooliitr — APPROVED** [review]

**Review by shazron — APPROVED** [review]

**Pull request merged**
